defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

collections:
  tags:
    output: true
    permalink: tags/:path/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

feed:
  tags: true

url: https://grossack.site
title: "Chris Grossack's Blog"
